baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Golf MK3 GTI TFSI Swap'
theme = 'hugo-book'


[[module.imports]]
path = 'github.com/hugomods/icons/vendors/bootstrap'
[[module.imports]]
path = 'github.com/hugomods/images'
[[module.imports]]
path = 'github.com/hugomods/bootstrap'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true